routes/index.py
import uuid

from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort, current_app, Response)

from models.city import City
from models.college import College
from models.message import Messages
from models.topic.board import BoardChoice
from models.topic.topic import Topic
from models.user import User
from routes.helper import new_csrf_token, new_reset_password_token, cache, add_session, get_session, current_user
from routes.privilege_decorator import csrf_required, login_required
from utils import log, map_user_role, random_string

main = Blueprint('index', __name__)


"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


@main.route('/')
def index():
    pts = Topic.latest_eight_by_board(board=BoardChoice.parent_topic.name)
    cts = Topic.latest_eight_by_board(board=BoardChoice.child_topic.name)
    ps = Topic.latest_eight_by_board(board=BoardChoice.post.name)
    log('pts, cts', len(pts), len(cts))
    u = current_user()
    cities = City.all()
    colleges = College.all()
    return render_template(
        "index.html",
        cities=cities,
        colleges=colleges,
        parent_topics=pts, child_topics=cts, posts=ps, user=u)


@main.route('/city/<int:id>')
def index_city(id):
    pts = Topic.latest_eight_by_board_mode_menu(id, menu='city', board=BoardChoice.parent_topic.name)
    cts = Topic.latest_eight_by_board_mode_menu(id, menu='city', board=BoardChoice.child_topic.name)
    ps = Topic.latest_eight_by_board_mode_menu(id, menu='city', board=BoardChoice.post.name)
    u = current_user()
    token = new_csrf_token()
    cities = City.all()
    colleges = College.all()
    return render_template(
        "index.html",
        token=token,
        cities=cities,
        colleges=colleges,
        parent_topics=pts, child_topics=cts, posts=ps, user=u)


@main.route('/college/<int:id>')
def index_college(id):
    pts = Topic.latest_eight_by_board_mode_menu(id, menu='college', board=BoardChoice.parent_topic.name)
    cts = Topic.latest_eight_by_board_mode_menu(id, menu='college', board=BoardChoice.child_topic.name)
    ps = Topic.latest_eight_by_board_mode_menu(id, menu='college', board=BoardChoice.post.name)
    u = current_user()
    token = new_csrf_token()
    cities = City.all()
    colleges = College.all()
    return render_template(
        "index.html",
        token=token,
        cities=cities,
        colleges=colleges,
        parent_topics=pts, child_topics=cts, posts=ps, user=u)


@main.route("/register/view")
def register_view():
    u = current_user()
    token = new_csrf_token()
    return render_template("register.html",
                           map_user_role=map_user_role,
                           token=token, user=u)


@main.route("/login/view")
def login_view():
    u = current_user()
    token = new_csrf_token()
    return render_template("login.html", token=token, user=u)


@main.route("/login", methods=['POST'])
@csrf_required
def login():
    form = request.form
    user = User.one(username=form['username'])
    u = User.validate_login(form)
    # print('login user <{}>'.format(u))
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('.index'))
    else:
        redirect_to_index = redirect(url_for('.index'))
        response = current_app.make_response(redirect_to_index)

        ran_str = random_string()
        session_id = add_session(ran_str, str(u.id))
        response.set_cookie('session_id', value=session_id)

        return response


@main.route("/logout", methods=['GET', 'POST'])
@login_required
def logout():
    session_id = request.cookies.get('session_id', default='')
    log('logout session_id <{}>'.format(session_id))
    if cache.exists(session_id):
        cache.delete(session_id)
        redirect_to_index = redirect(url_for('.index'))
        response: Response = current_app.make_response(redirect_to_index)
        response.delete_cookie('session_id')
        return response
    else:
        log('logout failed')
        return redirect(url_for('.index'))


@main.route("/password/to_reset/view")
def password_to_reset_view():
    u = User.guest()
    return render_template("password_to_reset_view.html", user=u)


@main.route("/password/reset/send", methods=['POST'])
@login_required
def reset_send():
    form = request.form.to_dict()
    u = User.one(username=form['username'])
    if u is None:
        abort(404)
    else:
        token = new_reset_password_token(u.id)
        Messages.send(
            title='{} 更改密码'.format(u.username),
            content='https://www.chenyehong.com/password/reset/view?token={}'.format(token),
            # 从 admin email 发到 user email, 现在只有一个
            sender_id=u.id,
            receiver_id=u.id
        )
    return redirect(url_for('.index'))


@main.route("/password/reset/view")
def password_reset_view():
    token = request.args['token']
    log('token', token)

    if cache.exists(token):
        return render_template(
            'password_reset_view.html',
            user=User.guest(),
            token=token,
        )
    else:
        abort(404)


@main.route("/password/reset", methods=['POST'])
def password_reset():
    form = request.form.to_dict()
    password = form['password']
    token = form['token']

    if cache.exists(token):
        user_id = int(cache.get(token).decode(encoding='utf-8'))
        cache.delete(token)
        password = User.salted_password(password)
        User.update(user_id, password=password)
        u = User.one(id=user_id)
        return redirect(url_for('index.index'))
    else:
        abort(404)


@main.route("/register", methods=['POST'])
@csrf_required
def register():
    # form = request.args
    form = request.form.to_dict()
    # 用类函数来判断
    u = User.register(form)
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('.index'))
    else:
        session_id = random_string()
        add_session(session_id, u.id)
        return redirect(url_for('.index'))


def not_found(e):
    return render_template('404.html')

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>switch_home</title>
    <link rel="stylesheet" href="/static/css/bootstrap.4.3.1.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/switch_home.css">
</head>
<body>
{#{% include 'include/loading-animate.html' %}#}
{% from 'macro.html' import sh_platform, sh_community %}
{% include 'include/header.html' %}
<div class="sh-container container">
    {{ sh_platform(posts) }}
    {{ sh_community(parent_topics, child_topics) }}
    <div id="id-sh-create-topic" class="sh-right-fixed-bar hover-moveout" style="top: 40%; right: 0px; display: block; width: auto; background-color: #80bd01; color: white; padding-right: 20px;
    padding-left: 20px;">
        发布话题或寄宿信息
    </div>
</div>
{% include 'include/footer.html' %}

<script src="/static/js/jquery.3.1.1.js"></script>
<script src="/static/js/popper.min.1.14.7.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="/static/js/bootstrap.min.4.3.1.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script>
    let appendMask = function() {
        $('body').append(`<div id="id-mask"></div>`)
        $('#id-mask').click(function(){
            $('#id-mask').remove()
            $('#id-details').remove()
        })
    }

    let appendWarning = function() {
        let template = `                <div id="id-details">
                    <div class="panel">
                        <div class="header">
                            <span class="col_fade">警告</span>
                        </div>
                        <div class="inner">
                            <div class="form-group">
                                <label class="control-label text-success" for="inputSuccess1">声明</label>
                                <p>目前网站尚未真正上线, 网站内数据均为测试数据, 请不要相信, 感谢您访问, 希望喜欢我的想法.</p>
                            </div>
                        </div>
                    </div>
                </div>
`

        $('body').append(template)
    }

    let bindEvents = function() {
        $('#sh-platform-header').click(function(){
            window.location.href='/post'
        })
        $('#sh-child-header, #sh-parent-header').click(function(){
            window.location.href='/topic'
        })
        $('#id-sh-create-topic').click(function(){
            window.location.href='/topic/new'
        })
    }

    let showWarning = function() {
        appendMask()
        appendWarning()
    }

    let __main = function () {
        bindEvents()
        showWarning()
    }

    __main()

</script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.4.3.1.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/switch_home.css">
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
{% include 'include/header.html' %}
<div class="sh-container container">
    <div id="id-form-container">

        <form class="form-horizontal" method="post" action="{{ url_for('index.login', token=token) }}">
            <div class="form-group">
                <label class="control-label text-success" for="inputSuccess1">用户名</label>
                <input name="username" type="text" class="border-success form-control" id="inputSuccess1" aria-describedby="helpBlock2">
                {#                <span id="helpBlock2" class="help-block">A block of help text that breaks onto a new line and may extend beyond one line.</span>#}
            </div>
            <div class="form-group">
                <label class="control-label text-success" for="inputSuccess1">密码</label>
                <input name="password" type="text" class="border-success form-control" id="inputSuccess1" aria-describedby="helpBlock2">
                {#                <span id="helpBlock2" class="help-block">A block of help text that breaks onto a new line and may extend beyond one line.</span>#}
            </div>
            <div class="form-group">
                <input type="submit" class="span-primary" value="登录">
                {#                <span id="helpBlock2" class="help-block">A block of help text that breaks onto a new line and may extend beyond one line.</span>#}
            </div>
            <a href="/password/to_reset/view">忘记密码</a>
        </form>
    </div>
</div>
{% include 'include/footer.html' %}
<script src="/static/js/jquery.3.1.1.js"></script>
<script src="/static/js/popper.min.1.14.7.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="/static/js/bootstrap.min.4.3.1.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/macro.html
{% macro sh_platform(posts) -%}
    <div class="sh-platform sh-border-color-transform">
        <div id="sh-platform-header" class="sh-platform-header sh-header sh-background-color-transform">
            <h5 class="card-title">寄宿信息平台</h5>
        </div>
        <div id="sh-platform-posts" class="posts">
            {% for p in posts %}
                <div class="sh-post sh-background-color-transform" onclick=window.location.href='/topic/{{ p.id }}'>
                    <div class="card sh-card" style="width: 18rem;">
                        <div id="id-sh-card-img">
                            <img style="min-width: 288px; width: auto; height: 100%;" src='{{ p.cover_compressed }}' class="card-img-top" alt="...">
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">{{ p.title }}</h5>
                            <p class="card-text">{{ p.content | summary }}</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">{{ p.user().city() }}</small>
                            <small class="text-muted">-- {{ p.user().role_name() | identity }}</small>
                            <small class="text-muted">-- {{ p.user().username}}</small>
                            <br>
                            <small class="text-muted">{{ p.created_time | format_time }}</small>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% if posts | length == 8 %}
                {# 假如只有 8 个, 说明是在 index 主页, 那么就给一个 更多卡片 #}
                <div class="sh-post sh-background-color-transform" onclick=window.location.href='/post'>
                    <div class="card sh-card" style="width: 18rem;">

                        <div id="id-sh-card-img">
                            <img style="width: auto; height: 100%;" src='/static/img/house/h1.jpg' class="card-img-top" alt="...">
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">更多</h5>
                            <p class="card-text">{{ '............................................................' | summary }}</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">...</small>
                            <small class="text-muted">-- ...</small>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{%- endmacro %}

{% macro sh_community(parent_topics, child_topics) -%}
    <div class="sh-community-container">
        <div id="community-parents">
            <div id="sh-parent-header" class="sh-header header sh-background-color-transform">
                <h5 class="card-title">父母社区</h5>
            </div>

            <div class="panel">
                <div id="topic_list">
                    {% for t in parent_topics %}
                        <div class="cell">
                            <a class="user_avatar pull-left" href="/user/atian25">
                                <img src="{{ t.user().image }}" title="atian25">
                            </a>
                            <span class="reply_count pull-left">
                                  <span class="count_of_replies" title="回复数">
                                     {{ t.replies() | count }}
                                  </span>
                                  <span class="count_seperator">/</span>
                                  <span class="count_of_visits" title="点击数">
                                     {{ t.views }}
                                  </span>
                                  </span>
                            <a class="last_time pull-right" href="/topic/5cbfd9aca86ae80ce64b3175#5d544129697873456c6bd629">
                                <img class="user_small_avatar" src="{{ t.user().image }}">
                                <span class="last_active_time">{{ t.updated_time | format_time }}</span>
                            </a>
                            <div class="topic_title_wrapper">
                                <span class="put_top">置顶</span>
                                <a style="overflow: visible;" class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                    {{ t.title | topic_summary}}
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                    <div class="cell">
                        <div class="topic_title_wrapper">
                            <a style="overflow: visible;" class="topic_title" href="{{ url_for('topic.index') }}">
                                更多...
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="community-children">
            <div id="sh-child-header" class="sh-header header sh-background-color-transform">
                <h5 class="card-title">学生社区</h5>
            </div>

            <div class="panel">
                <div id="topic_list">
                    {% for t in child_topics %}
                        <div class="cell">
                            <a class="user_avatar pull-left" href="/user/{{ t.user().id }}">
                                <img src="{{ t.user().image }}" title="atian25">
                            </a>
                            <span class="reply_count pull-left">
                                  <span class="count_of_replies" title="回复数">
                                     {{ t.replies() | count }}
                                  </span>
                                  <span class="count_seperator">/</span>
                                  <span class="count_of_visits" title="点击数">
                                     {{ t.views }}
                                  </span>
                                  </span>
                            <a class="last_time pull-right" href="/user/{{ t.user().id }}">
                                <img class="user_small_avatar" src="{{ t.user().image }}">
                                <span class="last_active_time">{{ t.created_time | format_time }}</span>
                            </a>
                            <div class="topic_title_wrapper">
                                <span class="put_top">置顶</span>
                                <a style="overflow: visible;" class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                    {{ t.title | topic_summary }}
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                    <div class="cell">
                        <div class="topic_title_wrapper">
                            <a style="overflow: visible;" class="topic_title" href="{{ url_for('topic.index') }}">
                                更多...
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{%- endmacro %}

templates/password_reset_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.4.3.1.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/switch_home.css">
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
{% include 'include/header.html' %}
<div class="sh-container container">
    <div id="id-form-container">

        <form class="form-horizontal" method="post" action="{{ url_for('index.password_reset') }}">
            <div class="form-group">
                <label class="control-label text-success" for="inputSuccess1">新密码: </label>
                <input name="password" type="text" class="border-success form-control" id="inputSuccess1" aria-describedby="helpBlock2">
                <input type="hidden" name="token" value="{{ token }}">
                {#                <span id="helpBlock2" class="help-block">A block of help text that breaks onto a new line and may extend beyond one line.</span>#}
            </div>
            <div class="form-group">
                <input type="submit" class="span-primary" value="确认">
                {#                <span id="helpBlock2" class="help-block">A block of help text that breaks onto a new line and may extend beyond one line.</span>#}
            </div>
        </form>
    </div>

</div>
{% include 'include/footer.html' %}
<script src="/static/js/jquery.3.1.1.js"></script>
<script src="/static/js/popper.min.1.14.7.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="/static/js/bootstrap.min.4.3.1.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/password_to_reset_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.4.3.1.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/switch_home.css">
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
{% include 'include/header.html' %}
<div class="sh-container container">
    <div id="id-form-container">

        <form class="form-horizontal" method="post" action="{{ url_for('index.reset_send') }}">
            <div class="form-group">
                <label class="control-label text-success" for="inputSuccess1">输入要修改密码的用户名</label>
                <input name="username" type="text" class="border-success form-control" id="inputSuccess1" aria-describedby="helpBlock2">
                {#                <span id="helpBlock2" class="help-block">A block of help text that breaks onto a new line and may extend beyond one line.</span>#}
            </div>
            <div class="form-group">
                <input type="submit" class="span-primary" value="确认">
                {#                <span id="helpBlock2" class="help-block">A block of help text that breaks onto a new line and may extend beyond one line.</span>#}
            </div>
        </form>
    </div>
</div>
{% include 'include/footer.html' %}
<script src="/static/js/jquery.3.1.1.js"></script>
<script src="/static/js/popper.min.1.14.7.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="/static/js/bootstrap.min.4.3.1.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.4.3.1.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/switch_home.css">
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
{% include 'include/header.html' %}
<div class="sh-container container">
    <div id="id-form-container">

        <form class="form-horizontal" method="post" action="{{ url_for('index.register', token=token) }}">
            <div class="form-group">
                <label class="control-label text-success" for="inputSuccess1">用户名</label>
                <input name="username" type="text" class="border-success form-control" id="inputSuccess1" aria-describedby="helpBlock2">
                {#                <span id="helpBlock2" class="help-block">A block of help text that breaks onto a new line and may extend beyond one line.</span>#}
            </div>
            <div class="form-group">
                <label class="control-label text-success" for="inputSuccess1">密码</label>
                <input name="password" type="text" class="border-success form-control" id="inputSuccess1" aria-describedby="helpBlock2">
                {#                <span id="helpBlock2" class="help-block">A block of help text that breaks onto a new line and may extend beyond one line.</span>#}
            </div>
            <div class="form-group">
                <label class="control-label" for="inputSuccess1">邮箱</label>
                <input name="email" type="text" class="form-control" id="inputSuccess1" aria-describedby="helpBlock2" value="xxx">
                {#                <span id="helpBlock2" class="help-block">A block of help text that breaks onto a new line and may extend beyond one line.</span>#}
            </div>
            <div class="form-group">
                <label class="control-label" for="inputSuccess1">身份:</label>
                <br>
                {#                <span id="helpBlock2" class="help-block">A block of help text that breaks onto a new line and may extend beyond one line.</span>#}
                {% for role_name, role_value in map_user_role.items() %}
                    {% if role_name not in ('guest', 'unknown') %}
                        <input type="radio" name="role" value="{{ role_value }}">{{ role_name | identity }}<br>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="form-group">
                <label class="control-label" for="inputSuccess1">(孩子的)大学</label>
                <input name="college" type="text" class="form-control" id="inputSuccess1" aria-describedby="helpBlock2" value="Top3 前十">
                {#                <span id="helpBlock2" class="help-block">A block of help text that breaks onto a new line and may extend beyond one line.</span>#}
            </div>
            <div class="form-group">
                <label class="control-label" for="inputSuccess1">目前常住城市 (例: 学生为大学所在城市, 父母为目前住址)</label>
                <input name="city" type="text" class="form-control" id="inputSuccess1" aria-describedby="helpBlock2" value="某线城市">
                {#                <span id="helpBlock2" class="help-block">A block of help text that breaks onto a new line and may extend beyond one line.</span>#}
            </div>
            <input type="submit" class="span-primary" value="注册">
        </form>
    </div>
</div>
{% include 'include/footer.html' %}
<script src="/static/js/jquery.3.1.1.js"></script>
<script src="/static/js/popper.min.1.14.7.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="/static/js/bootstrap.min.4.3.1.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>